# Generated by Django 3.0.7 on 2021-03-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_link', '0002_auto_20210321_0018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('transaction_id', 'account')},
        ),
    ]
